name: kubetest2-tf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'kubetest2-tf/go.mod'

    - run: go version

    - name: Build
      run: cd kubetest2-tf;go build -v .
